### PR TITLE
Create Insertion.cpp

### PR DESCRIPTION
**Pull request by shubhamsharma6701**
I have written the C++ code for pushing of elements in a deque through an array.

### CODE REVIEW

**Review by Ankit152 — CHANGES_REQUESTED** [review]
Try to give some comments.

**Comment by shubhamsharma6701** [comment]
I have added certain comments, you may see.

**Review by Ankit152 — APPROVED** [review]

**Comment by shubhamsharma6701** [comment]
Put this Insertion.cpp in the 'deque' folder, I can work on other codes as well like deleting, traversal and other operations.

**Comment by Ankit152** [comment]
@shubhamsharma6701 you should have placed it in the right folder.

**Comment by shubhamsharma6701** [comment]
I am actually new to open source programming like this and also I cannot find the 'deque' folder on my local machine.

**Comment by shubhamsharma6701** [comment]
Ok, we can do this. I can delete that file Insertion.cpp and push another file in the right folder through GitHub only. You may pull that one. Ok?

**Comment by Ankit152** [comment]
Okay. sure. You can do it in your next pull as well by providing deletion, traversal and other operations. please note that before working on these please create the issue so that i can assign them to you.

**Pull request merged**
